version: 0.2

env:
  variables:
    ECR_REGISTRY: "389560765612.dkr.ecr.ap-south-1.amazonaws.com/phpwebappprivate"
    DOCKER_IMAGE_NAME: "phpwebapp"

phases:
  build:
    commands:
    - echo "Build phase"
    - export AWS_ECR_PASSWORD=$(aws ecr-public get-login-password --region ap-south-1)
    - echo $AWS_ECR_PASSWORD | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker tag $DOCKER_IMAGE_NAME:latest $ECR_REGISTRY/$DOCKER_IMAGE_NAME:latest
    - docker push $ECR_REGISTRY/$DOCKER_IMAGE_NAME:latest

  post_build:
    commands:
    - echo "Build successfully completed"
